### ISSUE TITLE
Crash  - CRITICAL:root:'albumNameEnc'

### ISSUE THREAD

**Issue by JohnSeals** [Zebradil/Gimme-iPhotos#11]
Righ after the app reports 'Downloading all photos into '/home/xxxxxx/Pictures' while skipping existing…' the app crashes and I see this error:
CRITICAL:root:'albumNameEnc'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gimme_iphotos/__init__.py", line 81, in main
    DownloaderApp(vars(args)).run()
  File "/usr/local/lib/python3.9/site-packages/gimme_iphotos/downloader.py", line 108, in run
    icloud_photos = self.download_photos(
  File "/usr/local/lib/python3.9/site-packages/gimme_iphotos/downloader.py", line 182, in download_photos
    api.photos.all,
  File "/usr/local/lib/python3.9/site-packages/pyicloud/services/photos.py", line 225, in all
    return self.albums["All Photos"]
  File "/usr/local/lib/python3.9/site-packages/pyicloud/services/photos.py", line 186, in albums
    folder["fields"]["albumNameEnc"]["value"]
KeyError: 'albumNameEnc'

Thanks!

**Comment by mercs600** [comment]
The same issue here, I saw the solution to override photos service in pycloud but I wanted to run it on your docker - how to fix it ?

**Comment by Zebradil** [comment]
Hey, sorry for the delay. This should be fixed in pyicloud, I just need to update dependency. I'll try to do it today.

**Comment by Zebradil** [comment]
Well, it was more complicated than I expected. I had to fork pyicloud to create a new release with required fix.

The new version is published on PYPI: `gimme-iphotos==1.0.8.1`
The new docker image: `zebradil/gimme-iphotos:1.0.8.1`

This fixed the error in my tests, reopen if there are still some issues.
