### ISSUE TITLE
Cannot use app specific password in docker?

### ISSUE THREAD

**Issue by liquidtoon01** [Zebradil/Gimme-iPhotos#29]
Hi, I'm trying to use an app specific password to negate the need for MFA, but i am getting the following error;

```
CRITICAL:root:'dsInfo'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gimme_iphotos/__init__.py", line 81, in main
    DownloaderApp(vars(args)).run()
  File "/usr/local/lib/python3.9/site-packages/gimme_iphotos/downloader.py", line 106, in run
    api = self.connect_to_icloud(config)
  File "/usr/local/lib/python3.9/site-packages/gimme_iphotos/downloader.py", line 122, in connect_to_icloud
    api = PyiCloudService(config["username"], config["password"])
  File "/usr/local/lib/python3.9/site-packages/pyicloud/base.py", line 211, in __init__
    self.authenticate()
  File "/usr/local/lib/python3.9/site-packages/pyicloud/base.py", line 239, in authenticate
    self.params.update({"dsid": self.data["dsInfo"]["dsid"]})
KeyError: 'dsInfo'
```

Any ideas why this is happening? Happens when doing interactively or via config file

**Comment by deegs** [comment]
FWIW I get the same error when using an app specific password with a pip3 install but this seems to be an [upstream issue in pyicloud](https://github.com/picklepete/pyicloud/issues/349).
