### ISSUE TITLE
ImportError: cannot import name 'Callable' from 'collections'

### ISSUE THREAD

**Issue by arfbarky** [Zebradil/Gimme-iPhotos#93]
I setup a new desktop with Debian 12 which came with Python 3.11.2. I get this error:

`rob@corsair:~$ gimme-iphotos 
Traceback (most recent call last):
  File "/home/rob/.local/bin/gimme-iphotos", line 5, in <module>
    from gimme_iphotos import main
  File "/home/rob/.local/pipx/venvs/gimme-iphotos/lib/python3.11/site-packages/gimme_iphotos/__init__.py", line 9, in <module>
    from .downloader import DownloaderApp
  File "/home/rob/.local/pipx/venvs/gimme-iphotos/lib/python3.11/site-packages/gimme_iphotos/downloader.py", line 11, in <module>
    from pyicloud import PyiCloudService
  File "/home/rob/.local/pipx/venvs/gimme-iphotos/lib/python3.11/site-packages/pyicloud/__init__.py", line 3, in <module>
    from pyicloud.base import PyiCloudService
  File "/home/rob/.local/pipx/venvs/gimme-iphotos/lib/python3.11/site-packages/pyicloud/base.py", line 20, in <module>
    from pyicloud.services import (
  File "/home/rob/.local/pipx/venvs/gimme-iphotos/lib/python3.11/site-packages/pyicloud/services/__init__.py", line 8, in <module>
    from pyicloud.services.account import AccountService
  File "/home/rob/.local/pipx/venvs/gimme-iphotos/lib/python3.11/site-packages/pyicloud/services/account.py", line 6, in <module>
    from pyicloud.utils import underscore_to_camelcase
  File "/home/rob/.local/pipx/venvs/gimme-iphotos/lib/python3.11/site-packages/pyicloud/utils.py", line 3, in <module>
    import keyring
  File "/home/rob/.local/pipx/venvs/gimme-iphotos/lib/python3.11/site-packages/keyring/__init__.py", line 6, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/home/rob/.local/pipx/venvs/gimme-iphotos/lib/python3.11/site-packages/keyring/core.py", line 14, in <module>
    from . import backend
  File "/home/rob/.local/pipx/venvs/gimme-iphotos/lib/python3.11/site-packages/keyring/backend.py", line 18, in <module>
    from .util import properties
  File "/home/rob/.local/pipx/venvs/gimme-iphotos/lib/python3.11/site-packages/keyring/util/properties.py", line 1, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.11/collections/__init__.py)`

I am not a coder, how can I fix this?

**Comment by Zebradil** [comment]
Hi,

I think you can't do much with this except run the program with an older version of Python (using pyenv, for example). I'll need to update it to support the latest Python, but I can't estimate when that'll be done.

The easiest way to still run it is to use docker to run the program. Here is how to do that: https://github.com/Zebradil/Gimme-iPhotos#docker

**Comment by arfbarky** [comment]
Okie doke, I was confused by the example Docker command, but I got it figured out. Thanks!
